name: Build and push WildFly Docker images

# This action requires 4 secrets:
# secrets.REGISTRY          - the container registry (e.g. quay.io)
# secrets.IMAGE             - the namespaced name of the image (e.g. wildfly/wildfly)
# secrets.REGISTRY_USER     - the user name to authentication before pushing the image
# secrets.REGISTRY_PASSWORD - the user password to authentication before pushing the image

on:
  push:
    tags-ignore:
      - "26*"
env:
  WILDFLY_VERSION: 33.0.1.Final
  WILDFLY_SHA1: 943ec801bf65bb42de27ef78c85d325180dcab0d
  
jobs:
  wildfly-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Download wildfly
        run: |
          curl -L -O https://github.com/wildfly/wildfly/releases/download/${{ env.WILDFLY_VERSION }}/wildfly-${{ env.WILDFLY_VERSION }}.tar.gz \
            && sha1sum wildfly-${{ env.WILDFLY_VERSION }}.tar.gz | grep ${{ env.WILDFLY_SHA1 }}
      - name: Upload WildFly distribution
        uses: actions/upload-artifact@v4
        with:
          name: wildfly-dist
          path: wildfly-${{ env.WILDFLY_VERSION }}.tar.gz
  image:
    needs: wildfly-dist
    env:
      # Put the "latest" tag on this JDK version
      JDK_VERSION_FOR_LATEST: 21
    strategy:
      matrix:
        include:
          - jdk-version: 11
            dist: ubi9-minimal
            platforms: linux/amd64,linux/arm64,linux/ppc64le
          - jdk-version: 17
            dist: ubi9-minimal
            platforms: linux/amd64,linux/arm64,linux/ppc64le
          - jdk-version: 21
            dist: ubi9-minimal
            platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
    environment: quay.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.4
      - name: Download WildFly distribution
        uses: actions/download-artifact@v4
        with:
          name: wildfly-dist
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag,suffix=-jdk${{ matrix.jdk-version }}
            type=raw,value=latest,suffix=-jdk${{ matrix.jdk-version }}
            type=raw,value=latest,enable=${{ matrix.jdk-version == env.JDK_VERSION_FOR_LATEST }}
          labels: |
            org.opencontainers.image.jdk-version=${{ matrix.jdk-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Docker Login to Quay.io
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push JDK images
        id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          build-args: |
            jdk=${{ matrix.jdk-version }}
            dist=${{ matrix.dist }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}